install:
  - cmd: git submodule -q update --init

image:
  - Visual Studio 2017
  - Ubuntu

configuration:
  - release

before_build:
  # Prepare the out-of-source build directory.
  - mkdir build
  - git submodule update --init --recursive
  - cmd: set Path=C:/Qt/Tools/mingw530_32/bin;%Path%
  - cmd: set CC=C:/Qt/Tools/mingw530_32/bin/gcc.exe
  - cmd: set CXX=C:/Qt/Tools/mingw530_32/bin/g++.exe
  - cmd: curl -L --silent --show-error --output VulkanSDK.exe https://vulkan.lunarg.com/sdk/download/1.0.65.1/windows/VulkanSDK-1.0.65.1-Installer.exe?Human=true
  - cmd: VulkanSDK.exe /S
  - cmd: set VK_SDK_PATH=C:/VulkanSDK/1.0.65.1
  - sh:  wget -O vulkansdk-linux-x86_64-1.0.65.0.run https://vulkan.lunarg.com/sdk/download/1.0.65.0/linux/vulkansdk-linux-x86_64-1.0.65.0.tar.gz?Human=true
  - sh:  tar -xzf vulkansdk-linux-x86_64-1.0.65.0.tar.gz
  - sh:  chmod ugo+x vulkansdk-linux-x86_64-1.0.65.0.run
  - sh:  ./vulkansdk-linux-x86_64-1.0.65.0.run
  - sh:  export VK_SDK_PATH=%APPVEYOR_BUILD_FOLDER%/VulkanSDK/1.0.65.0/x86_64

build_script:
  - cmake --version
  - gcc   --version
  - g++   --version
  - cmd: cmake -H. -Bbuild -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DBUILD_EXTRAS:BOOL=OFF" "-DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo" "-DCMAKE_PREFIX_PATH:STRING=C:/Qt/5.9.1/mingw53_32" "-DCMAKE_MAKE_PROGRAM:STRING=C:/Qt/mingw530_32/bin/mingw32-make.exe"
  - sh:  cmake -H. -Bbuild -DBUILD_EXTRAS:BOOL=OFF -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo
  - cmake --build ./build --target all

after_build:
  - cmd: echo gothic-win32-v%appveyor_build_version% >> VERSION
  - cmd: echo gothic-linux-v%appveyor_build_version% >> VERSION
  - set name="bin/open_gothic.zip"
  - cmd: copy /b/y "build\lib\MoltenTempest\bin\libMoltenTempest.dll" "bin\libMoltenTempest.dll"
  - cmd: copy /b/y "C:\Qt\Tools\mingw530_32\bin\libgcc_s_dw2-1.dll"   "bin\libgcc_s_dw2-1.dll"
  - cmd: copy /b/y "C:\Qt\Tools\mingw530_32\bin\libstdc++-6.dll"      "bin\libstdc++-6.dll"
  - cmd: copy /b/y "C:\Qt\Tools\mingw530_32\bin\libwinpthread-1.dll"  "bin\libwinpthread-1.dll"
  - sh:  cp        "build/lib/MoltenTempest/bin/libMoltenTempest.dll" "bin/libMoltenTempest.dll"
  - 7z a %name%    VERSION
  - 7z a %name%    "bin/shader/*.sprv"
  - 7z a %name%    "bin/data/*"
  - 7z a %name% -r "bin/*.exe"
  - 7z a %name% -r "bin/*.dll"

artifacts:
  - path: bin/open_gothic.zip
    name: archive

deploy:
  release: gothic-win32-v$(appveyor_build_version)
  description: 'no release description'
  provider: GitHub
  auth_token:
    secure: YLdtUMsAcc8FUr3kgwhQW7nkl5jDpLKbelvzWzzTWUfAiDd92Kd15rjlDJVEEFzo
  artifact: archive
  draft: true
  force_update: true
  prerelease: true
  on:
    branch: master                # release from master branch only
    appveyor_repo_tag: true       # deploy on tag push only
